n = input('Digite Algo: ')
print('O tipo primitido de {} é '.format(n),type(n))
print('Só tem espaço no valor {} ?'.format(n), n.isspace())
print('O valor {} é um número ?'.format(n), n.isnumeric())
print('O valor {} é alfabético ?'.format(n), n.isalpha())
print('O valor {} é Alfanumérico ?'.format(n), n.isalnum())
print('O valor {} só tem letras maiúsculas ?'.format(n), n.isupper())
print('O valor {} só tem letras minusculas ?'.format(n), n.islower())
print('O valor {} possui letras maiúsculas e minusculas ?'.format(n), n.istitle())
